version: '3.8'

services: 
    server:
        container_name: workshop-server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
        volumes: 
            - ./server:/app
    
    client:
        container_name: workshop-client
        build:
            context: ./client
            dockerfile: Dockerfile
        stdin_open: true
        ports: 
            - 3000:3000
        volumes:
            - ./client:/app
            - /app/node_modules

        
